import yfinance as yf
import pandas as pd
import time
import requests
import io
import datetime
import concurrent.futures
import json
import os
import warnings

# --- CONFIGURATION ---
BATCH_SIZE = 50         
LOOKBACK_DAYS = 5       
SLEEP_TIME = 2          
MAX_WORKERS = 5         
MAX_RETRIES = 3         
OUTPUT_FILENAME = "index.html" 

warnings.simplefilter(action='ignore', category=FutureWarning)

# --- HTML TEMPLATE ---
HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daily Market Scan</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/lucide@latest"></script>
    <style>
        .scrollbar-hide::-webkit-scrollbar { display: none; }
        .scrollbar-hide { -ms-overflow-style: none; scrollbar-width: none; }
    </style>
</head>
<body class="bg-slate-900 text-slate-200 font-sans min-h-screen p-6">
    <div class="max-w-7xl mx-auto">
        <header class="flex justify-between items-center mb-8 border-b border-slate-700 pb-4">
            <div>
                <h1 class="text-3xl font-bold text-blue-400 flex items-center gap-2">
                    <i data-lucide="crosshair" class="w-8 h-8"></i> Market Sniper & Scanner
                </h1>
                <p class="text-slate-400 text-sm mt-1">Trend Following (Crosses) + Sniper (RSI > 70 & High Vol)</p>
            </div>
            <div class="text-right">
                <div class="text-sm text-slate-500 italic">Updated: <span id="gen-date" class="text-slate-300"></span></div>
                <div class="text-xs text-slate-600 mt-1">Click tickers for TradingView</div>
            </div>
        </header>

        <!-- Stats Cards -->
        <div id="stats-container" class="grid grid-cols-1 md:grid-cols-4 gap-4 mb-8">
            <div class="bg-slate-800 p-4 rounded-lg border-l-4 border-blue-500 shadow-lg">
                <div class="text-slate-400 text-xs uppercase font-bold">Total Setups</div>
                <div class="text-2xl font-bold text-white" id="stat-total">0</div>
            </div>
            <div class="bg-slate-800 p-4 rounded-lg border-l-4 border-purple-500 shadow-lg">
                <div class="text-slate-400 text-xs uppercase font-bold">Sniper Setups (High Conviction)</div>
                <div class="text-2xl font-bold text-purple-400" id="stat-sniper">0</div>
            </div>
            <div class="bg-slate-800 p-4 rounded-lg border-l-4 border-emerald-500 shadow-lg">
                <div class="text-slate-400 text-xs uppercase font-bold">Bullish Crosses</div>
                <div class="text-2xl font-bold text-emerald-400" id="stat-bull">0</div>
            </div>
            <div class="bg-slate-800 p-4 rounded-lg border-l-4 border-red-500 shadow-lg">
                <div class="text-slate-400 text-xs uppercase font-bold">Bearish Crosses</div>
                <div class="text-2xl font-bold text-red-400" id="stat-bear">0</div>
            </div>
        </div>

        <!-- Filters -->
        <div id="filters-container" class="flex flex-wrap gap-4 mb-6">
            <input type="text" id="search-input" placeholder="Search Ticker..." class="bg-slate-800 border border-slate-700 rounded px-4 py-2 focus:outline-none focus:border-blue-500 text-sm transition-colors">
            <select id="category-filter" class="bg-slate-800 border border-slate-700 rounded px-4 py-2 text-sm focus:outline-none hover:bg-slate-700 transition-colors">
                <option value="all">All Strategies</option>
                <option value="Sniper">🎯 Sniper (High Conviction)</option>
                <option value="Bullish">🚀 Bullish Cross</option>
                <option value="Bearish">📉 Bearish Cross</option>
            </select>
        </div>

        <!-- Data Table -->
        <div class="overflow-x-auto bg-slate-800 rounded-lg shadow-xl" id="table-container">
            <table class="w-full text-left border-collapse">
                <thead>
                    <tr class="bg-slate-900 text-slate-400 text-xs uppercase tracking-wider border-b border-slate-700">
                        <th class="p-4 font-medium">Ticker</th>
                        <th class="p-4 font-medium">Strategy</th>
                        <th class="p-4 font-medium">Signal / Pattern</th>
                        <th class="p-4 font-medium">Price</th>
                        <th class="p-4 font-medium">Trend Info</th>
                        <th class="p-4 font-medium">Details</th>
                        <th class="p-4 font-medium">Date</th>
                    </tr>
                </thead>
                <tbody id="table-body" class="text-sm divide-y divide-slate-700">
                    <!-- Rows injected via JS -->
                </tbody>
            </table>
        </div>
        
        <footer class="mt-10 text-center text-slate-600 text-xs">
            Generated by Python Market Scanner
        </footer>
    </div>

    <script>
        // --- DATA INJECTION ---
        const embeddedData = /* DATA_PLACEHOLDER */;
        const generatedDate = "/* DATE_PLACEHOLDER */";

        // --- APP LOGIC ---
        if (typeof lucide !== 'undefined') lucide.createIcons();
        document.getElementById('gen-date').textContent = generatedDate;

        const tableBody = document.getElementById('table-body');
        const searchInput = document.getElementById('search-input');
        const categoryFilter = document.getElementById('category-filter');

        renderStats();
        renderTable();

        searchInput.addEventListener('input', renderTable);
        categoryFilter.addEventListener('change', renderTable);

        function renderStats() {
            document.getElementById('stat-total').textContent = embeddedData.length;
            
            const sniper = embeddedData.filter(r => r.Category.includes('Sniper')).length;
            const bull = embeddedData.filter(r => r.Category.includes('Bullish')).length;
            const bear = embeddedData.filter(r => r.Category.includes('Bearish')).length;

            document.getElementById('stat-sniper').textContent = sniper;
            document.getElementById('stat-bull').textContent = bull;
            document.getElementById('stat-bear').textContent = bear;
        }

        function renderTable() {
            const searchTerm = searchInput.value.toLowerCase();
            const catFilter = categoryFilter.value;

            const filtered = embeddedData.filter(row => {
                const matchesSearch = row.Ticker.toLowerCase().includes(searchTerm);
                let matchesCat = true;
                if (catFilter !== 'all') {
                    matchesCat = row.Category.includes(catFilter);
                }
                return matchesSearch && matchesCat;
            });

            if (filtered.length === 0) {
                tableBody.innerHTML = '<tr><td colspan="7" class="p-8 text-center text-slate-500 italic">No matches found.</td></tr>';
                return;
            }

            tableBody.innerHTML = filtered.map(row => {
                let badgeClass = "bg-slate-700 text-slate-300";
                if (row.Category.includes('Bullish')) badgeClass = "bg-emerald-900/50 text-emerald-400 border border-emerald-700";
                if (row.Category.includes('Bearish')) badgeClass = "bg-red-900/50 text-red-400 border border-red-700";
                if (row.Category.includes('Sniper')) badgeClass = "bg-purple-900/50 text-purple-400 border border-purple-700";

                const tvLink = `https://www.tradingview.com/chart/?symbol=${row.Ticker}`;

                return `
                    <tr class="hover:bg-slate-700/50 transition-colors group">
                        <td class="p-4 font-bold text-white">
                            <a href="${tvLink}" target="_blank" class="hover:text-blue-400 flex items-center gap-2 transition-colors">
                                ${row.Ticker} 
                                <i data-lucide="external-link" class="w-3 h-3 opacity-0 group-hover:opacity-100 transition-opacity"></i>
                            </a>
                        </td>
                        <td class="p-4"><span class="px-2 py-1 rounded text-xs font-medium ${badgeClass}">${row.Category}</span></td>
                        <td class="p-4 font-mono text-slate-300">${row.Signal}</td>
                        <td class="p-4 font-mono text-white">$${row.Price}</td>
                        <td class="p-4 text-slate-400">${row.AVWAP_Info}</td>
                        <td class="p-4 text-slate-400 text-xs max-w-xs truncate" title="${row.Details}">${row.Details}</td>
                        <td class="p-4 text-slate-500">${row.Date}</td>
                    </tr>
                `;
            }).join('');
            
            if (typeof lucide !== 'undefined') lucide.createIcons();
        }
    </script>
</body>
</html>
"""

# --- HELPERS ---
def get_sma(series, window):
    return series.rolling(window=window).mean()

def get_rsi(series, period=14):
    """Calculates RSI."""
    delta = series.diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=period).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=period).mean()
    rs = gain / loss
    return 100 - (100 / (1 + rs))

def calculate_anchored_vwap(df):
    """Calculates VWAP anchored to the highest volume day in the last 60 days."""
    try:
        recent_data = df.tail(60)
        max_vol_idx = recent_data['Volume'].idxmax()
        subset = df.loc[max_vol_idx:].copy()
        subset['PV'] = subset['Close'] * subset['Volume']
        subset['Cum_PV'] = subset['PV'].cumsum()
        subset['Cum_Vol'] = subset['Volume'].cumsum()
        subset['AVWAP'] = subset['Cum_PV'] / subset['Cum_Vol']
        
        latest_avwap = subset['AVWAP'].iloc[-1]
        anchor_date = max_vol_idx.date()
        return latest_avwap, str(anchor_date)
    except Exception:
        return None, None

# --- TICKER FETCHING ---
def get_nasdaq_composite_tickers():
    print("Fetching NASDAQ Composite list...")
    url = "https://www.nasdaqtrader.com/dynamic/symdir/nasdaqlisted.txt"
    try:
        response = requests.get(url, timeout=30)
        response.raise_for_status() # Check for errors
        df = pd.read_csv(io.StringIO(response.text), sep='|')
        if 'Test Issue' in df.columns: df = df[df['Test Issue'] == 'N']
        df = df.dropna(subset=['Symbol'])
        df = df[~df['Symbol'].astype(str).str.contains('File Creation')]
        return [str(t).replace('.', '-') for t in df['Symbol'].tolist()]
    except Exception as e:
        print(f"   [Error] Failed to fetch NASDAQ Composite: {e}")
        return []

def get_sp500_tickers():
    print("Fetching S&P 500 list...")
    url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
    try:
        response = requests.get(url, headers=headers, timeout=30)
        response.raise_for_status()
        
        tables = pd.read_html(io.StringIO(response.text))
        target_df = next((t for t in tables if 'Symbol' in t.columns or 'Ticker symbol' in t.columns), None)
        
        if target_df is None:
            print("   [Error] S&P 500 table not found on Wikipedia.")
            return []
            
        # Normalize column name if needed
        if 'Ticker symbol' in target_df.columns:
            target_df = target_df.rename(columns={'Ticker symbol': 'Symbol'})
            
        tickers = [str(t).replace('.', '-') for t in target_df['Symbol'].tolist()]
        print(f"   Found {len(tickers)} S&P 500 tickers.")
        return tickers
        
    except Exception as e:
        print(f"   [Error] Failed to fetch S&P 500: {e}")
        return []

# --- FUNDAMENTAL CHECK ---
def check_fundamentals(ticker, mode):
    try:
        time.sleep(0.5) 
        stock = yf.Ticker(ticker)
        fin = stock.quarterly_financials
        if fin.empty: return False, "No Data"
        fin = fin.T 
        fin.sort_index(ascending=False, inplace=True)
        fin = fin[~fin.index.duplicated(keep='first')]
        if len(fin) < 3: return False, "Insufficient Qs"

        try:
            r0 = fin['Total Revenue'].iloc[0]
            r1 = fin['Total Revenue'].iloc[1]
            r2 = fin['Total Revenue'].iloc[2]
        except: return False, "Rev Missing"

        if mode == 'bullish':
            if not (r0 > r1 and r1 > r2): return False, "Rev Not Growing"
        elif mode == 'bearish':
            if not (r0 < r1 and r1 < r2): return False, "Rev Not Declining"
            
        return True, "Passed"
    except Exception as e: return False, str(e)

# --- BATCH ANALYZER ---
def download_data_with_retry(tickers):
    for attempt in range(MAX_RETRIES):
        try:
            data = yf.download(tickers, period="1y", group_by='ticker', progress=False, threads=True, auto_adjust=True)
            return data
        except Exception:
            time.sleep(10 * (attempt + 1))
    return pd.DataFrame()

def analyze_batch(tickers):
    results_list = []
    trend_matches = [] 

    try:
        data = download_data_with_retry(tickers)
        if data.empty: return []

        for ticker in tickers:
            print(f"   Scanning: {ticker:<8}", end='\r', flush=True)
            try:
                # 1. PREPARE DATA
                if len(tickers) > 1:
                    if ticker not in data.columns.levels[0]: continue
                    df = data[ticker].copy()
                else:
                    df = data.copy()

                if df.empty or len(df) < 200: continue
                df.dropna(how='all', inplace=True)
                
                curr = df.iloc[-1]
                prev = df.iloc[-2]
                
                if curr['Close'] <= 5: continue

                # Indicators
                df['SMA50'] = get_sma(df['Close'], 50)
                df['SMA200'] = get_sma(df['Close'], 200)
                df['VolSMA50'] = get_sma(df['Volume'], 50)
                df['RSI'] = get_rsi(df['Close'])  # NEW: RSI
                
                # Bollinger Bands
                df['BB_Mid'] = df['Close'].rolling(window=20).mean()
                df['BB_Std'] = df['Close'].rolling(window=20).std()
                df['BB_Upper'] = df['BB_Mid'] + (2 * df['BB_Std'])

                sma50_val = df['SMA50'].iloc[-1]
                vol_sma_val = df['VolSMA50'].iloc[-1]
                
                if pd.isna(sma50_val) or pd.isna(vol_sma_val): continue
                if (sma50_val * vol_sma_val) < 20000000: continue

                # ---------------------------------------------------------
                # STRATEGY 1: SNIPER (Bearish Mean Reversion)
                # ---------------------------------------------------------
                is_sniper = False
                sniper_reasons = []
                
                # Filter 1: Extension (Price > 20% above SMA50)
                deviation_pct = (curr['Close'] - sma50_val) / sma50_val * 100
                
                # Filter 2: NEW RSI Check (> 70 Overbought)
                rsi_val = df['RSI'].iloc[-1]
                
                if deviation_pct > 20 and rsi_val > 65: # Slightly relaxed 65 to catch top
                    
                    # Filter 3: High Relative Volume (Selling Pressure)
                    avg_vol = df['VolSMA50'].iloc[-1]
                    rel_vol = curr['Volume'] / avg_vol
                    
                    if rel_vol > 1.2: # Must be higher than average volume
                        
                        # Filter 4: Candle Patterns
                        if curr['High'] >= df['BB_Upper'].iloc[-1]: sniper_reasons.append("Hit Upper BB")
                        if (curr['Open'] > prev['Close']) and (curr['Close'] < prev['Open']): sniper_reasons.append("Bearish Engulfing")
                        if (curr['Open'] < prev['Close']) and (curr['Close'] < curr['Open']): sniper_reasons.append("Gap Down")
                        
                        if sniper_reasons:
                            avwap, anchor_date = calculate_anchored_vwap(df)
                            is_sniper = True
                            
                            results_list.append({
                                'Ticker': ticker,
                                'Category': "Sniper (Bear)",
                                'Signal': ", ".join(sniper_reasons),
                                'Price': round(curr['Close'], 2),
                                'AVWAP_Info': f"RSI: {round(rsi_val)} | Vol: {round(rel_vol,1)}x",
                                'Details': f"Ext: {deviation_pct:.1f}% | AVWAP: {round(avwap,2) if avwap else 'N/A'}",
                                'Date': str(curr.name.date())
                            })

                # ---------------------------------------------------------
                # STRATEGY 2: TREND CROSS
                # ---------------------------------------------------------
                if not is_sniper:
                    subset = df.iloc[-(LOOKBACK_DAYS+1):]
                    if len(subset) > 2:
                        sma50_s = subset['SMA50'].values
                        sma200_s = subset['SMA200'].values
                        dates = subset.index

                        for i in range(1, len(sma50_s)):
                            if sma50_s[i-1] <= sma200_s[i-1] and sma50_s[i] > sma200_s[i]:
                                trend_matches.append({'Ticker': ticker, 'Mode': 'bullish', 'Price': curr['Close'], 'Date': str(dates[i].date())})
                                break
                            elif sma50_s[i-1] >= sma200_s[i-1] and sma50_s[i] < sma200_s[i]:
                                trend_matches.append({'Ticker': ticker, 'Mode': 'bearish', 'Price': curr['Close'], 'Date': str(dates[i].date())})
                                break

            except Exception: continue

        # --- PROCESS TREND MATCHES ---
        if trend_matches:
            with concurrent.futures.ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
                future_to_item = {executor.submit(check_fundamentals, item['Ticker'], item['Mode']): item for item in trend_matches}
                
                for future in concurrent.futures.as_completed(future_to_item):
                    item = future_to_item[future]
                    try:
                        passed, reason = future.result()
                        cat_label = f"{item['Mode'].capitalize()} (Confirmed)" if passed else f"{item['Mode'].capitalize()} (Speculative)"
                        
                        results_list.append({
                            'Ticker': item['Ticker'],
                            'Category': cat_label,
                            'Signal': "Golden Cross" if item['Mode']=='bullish' else "Death Cross",
                            'Price': round(item['Price'], 2),
                            'AVWAP_Info': "Trend Setup",
                            'Details': f"Fund: {reason}",
                            'Date': item['Date']
                        })
                    except Exception: continue

    except Exception: pass
    return results_list

def generate_dashboard_file(df):
    timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    json_data = df.to_json(orient='records')
    html_content = HTML_TEMPLATE.replace("/* DATA_PLACEHOLDER */", json_data)
    html_content = html_content.replace("/* DATE_PLACEHOLDER */", timestamp)
    
    with open(OUTPUT_FILENAME, "w", encoding="utf-8") as f:
        f.write(html_content)
    print(f"\n[SUCCESS] Dashboard generated: {OUTPUT_FILENAME}")

def main():
    print("1. S&P 500\n2. NASDAQ Composite (Auto)\n3. Test List")
    c = input("Select: ").strip()
    if c=='1': tickers = get_sp500_tickers()
    elif c=='2': tickers = get_nasdaq_composite_tickers()
    else: tickers = ["AAPL", "TSLA", "NVDA", "AMD", "GME", "AMC", "SPY"]
    
    if not tickers: return

    print(f"\n--- Scanning {len(tickers)} Stocks (Dual Engine) ---")
    all_results = []
    
    for i in range(0, len(tickers), BATCH_SIZE):
        batch = tickers[i : i + BATCH_SIZE]
        print(f"\n[Batch {i}-{min(i+BATCH_SIZE, len(tickers))}] Processing...")
        res = analyze_batch(batch)
        all_results.extend(res)
        if i + BATCH_SIZE < len(tickers): time.sleep(SLEEP_TIME)

    if all_results:
        df = pd.DataFrame(all_results)
        generate_dashboard_file(df)
        print("Summary:")
        print(df['Category'].value_counts().to_string())
    else:
        print("No setups found today.")

if __name__ == "__main__":
    main()
